backupDestination: /var/backups
database: postgresql # or mysql - default is postgresql
runEveryCron: "@every 1m" # run every minute
databases: # all databases if empty
  - db1
  - db2
exclude: # databases to be excluded
  - db3
  - db4
format:
  gzip
  # gzip or 7zip. gzip if empty
  # gzip for postgresql doesn't use gzip directly but uses custom format to take sql dump with the same algorithm as gzip
  # for mysql; if encryption is enabled, it will use 7zip even if the format is gzip
backupAsTables: false # Backup MySQL databases as tables
removeLocal: true
archivePass: # Password for encrypting backups. No encryption if empty
retry: false
partSize: 64
rotation:
  enabled: true
  period: week # week or month - week db-week_1.sql.7z .. db-week_52.sql.7z - month db-january.sql.7z .. db-december.sql.7z
  suffix: day # day, hour or minute - day db-monday.sql.7z - hour db-monday-15.sql.7z - minute db-monday-15-30.sql.7z
  keep:
    daily: 7
    weekly: 4
    monthly: 3
remote:
  isRemote: false # for mysql; even if isRemote false and you are backing up as the msyql user in the local machine, you still have to provide user and password/
  host: 127.0.0.1
  port: 5432
  user: postgres # necessary for mysql, even if isRemote false
  password: password # necessary for mysql, even if isRemote false
backupType:
  type: minio
  info:
    - endpoint: minio endpoint
      region: minio region
      bucket: minio bucket
      path: backup path
      accessKey: minio access key
      secretKey: minio secret key
      secure: false
      insecureSkipVerify: false
  # type: s3
  # info:
  #   - region: aws region
  #     bucket: s3 bucket
  #     path: backup path
  #     accessKey: s3 access key
  #     secretKey: s3 secret key
  # type: sftp
  # info:
  #   - targets:
  #       - user: username
  #         host: ssh.example.com
  #         path: /var/backups
  #         port: 22
  #       - user: username2
  #         host: ssh.example2.com
  #         path: /var/backups
  #         port: 22
  # type: rsync
  # info:
  #   - targets:
  #       - user: username
  #         flags: "-a"
  #         host: ssh.example.com
  #         path: /var/backups
  #         port: 22
  #       - user: username2
  #         flags: "-a"
  #         host: ssh.example2.com
  #         path: /var/backups
  #         port: 22
notify:
  UptimeAlarm: true
  UptimeStartLimit: 6
  email:
    enabled: false
    onlyOnError: false
    insecureSkipVerify: false
    info:
      smtpHost: smtp.gmail.com
      smtpPort: 587
      username: sender@example.com
      from: sender@example.com
      password: 123456
      to: recipient@example.com
    error:
      smtpHost: smtp.gmail.com
      smtpPort: 587
      username: sender@example.com
      from: sender@example.com
      password: 123456
      to: recipient@example.com
  webhook:
    enabled: false
    onlyOnError: false
    serverIdentifier: test-server
    info:
      - https://webhook_url.example1.com
      - https://webhook_url.example2.com
    error:
      - https://webhook_url.example1.com
      - https://webhook_url.example2.com

log:
  enabled: true
  file: /var/log/monodb-backup.log
